"""new job

Revision ID: 860adbff50af
Revises: 59f1be6d3be8
Create Date: 2026-05-18 17:09:25.782729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '860adbff50af'
down_revision = '59f1be6d3be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listener', schema=None) as batch_op:
        batch_op.alter_column('job',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listener', schema=None) as batch_op:
        batch_op.alter_column('job',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
